name: Send payload

on:
  push:
    branches: [ "${{ toJson(github.event.repository.default_branch) }}" ]
  pull_request:
    branches: [ "${{ github.event.repository.default_branch }}" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - run: >-
          curl -X POST -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: ${{ secrets.GIT_TOKEN }}' -d '{"event_type": "import-to-snyk", "client_payload":{"org name":"Test org", "repo name": ${{ toJson(github.event.repository.name) }}, "default branch": ${{ toJson(github.event.repository.default_branch) }}, "archived": ${{ toJson(github.event.repository.archived) }}}}' https://api.github.com/repos/swahab-r7/test-repo/dispatches
